### ISSUE TITLE
How to prevent rsc_card / rsc_grid becoming toc items?

### ISSUE THREAD

**Issue by lgeistlinger** [rstudio/connectwidgets#60]
Hi I am using:

```
output:
  html_document:
    theme:
      bootswatch: lumen
    toc: yes 
    toc_float: yes 
    toc_depth: 3
```

in my yaml header. 

When I use `rsc_card` or `rsc_grid` the contents are automatically becoming level 2 toc items which is undesired in my case. This does not happen for `rsc_table`.
